name: Build and deploy to Kamereo EKS 

on:
  push:
    branches:
      - main
      - master
      - qa

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: kamereo/shared-workflows/.github/workflows/pipeline.yml@main